Closes #34
Mika215/hyf-website-group-2 pull request #100
Opened 2021-02-22 19:02 UTC by alinamarasca

add 4 headers and paragraphs into 'our impact' section

2021-02-22 21:56 UTC, erkamguresen requested changes

2021-02-22 21:56 UTC, erkamguresen commented on index.html
> +</section>
</section> should have indent.

2021-02-24 09:11 UTC, sheybusta approved these changes
good!

2021-02-24 11:02 UTC, erkamguresen approved these changes

2021-02-24 11:03 UTC, merged